### ISSUE TITLE
Crypto PRNG?

### ISSUE THREAD

**Issue by ChrisPattison** [thompsonsed/RandomNumberGeneration#1]
Hi! I think this is a cool project! Have you thought about benchmarking an AES counter-based PRNG implementation that uses the Intel AES-NI instructions? Intel gave some benchmarks in their whitepaper that shows encryption at about 1.3 cycles/byte which makes me think it might actually be fairly competitive with some of the other PRNGs

https://en.wikipedia.org/wiki/AES_instruction_set
https://www.intel.com/content/dam/doc/white-paper/advanced-encryption-standard-new-instructions-set-paper.pdf

**Comment by thompsonsed** [comment]
Thanks! It's a good idea. The AES-based approach is interesting.

This project was just something I used a couple of years back to pick a PRNG for my simulations. As that work is complete, I'm not going to be testing any PRNGs in the near future, so won't be implementing this. It's also definitely not my area of expertise! Feel free to fork the repo/submit a PR/otherwise use the code if you'd like to test it yourself.
